### ISSUE TITLE
Check boxes and radio buttons not working?

### ISSUE THREAD

**Issue by jeet-parekh** [papercss/papercss#147] opened 2018-04-20 09:42 UTC
Awesome project! Thanks for creating and sharing it.

The check boxes and radio buttons aren't working. There isn't any change in them after clicking. Even on the website https://www.getpapercss.com/docs/components/forms/.

I was wondering if it's broken, or is there some attribute to enable it?

**Comment by TotomInc** [comment] 2018-04-20 09:56
What browser are you using? I have just tried on IE 9 and it doesn't seem to work

**Comment by jeet-parekh** [comment] 2018-04-20 09:59
I'm on firefox 59.0.2

**Comment by koester** [comment] 2018-04-20 10:13
Tested it on chrome mobile and it's working as intended. What behavior did you see and what did you expect?

**Comment by TotomInc** [comment] 2018-04-20 10:16
I think it's when clicking on the radio button, it still looks empty. I got this bug with IE 9. What is strange is that Firefox just lose the support for this? IIRC, it always worked well with Firefox and Chrome.

**Comment by jeet-parekh** [comment] 2018-04-20 11:55
Exactly that. The check boxes and radio buttons look empty after clicking.

**Comment by 2020-abhilash** [comment] 2018-08-16 00:04
I did see this behavior in Chrome for about 10 seconds it didn't work and while clicking on the checkboxes and radio buttons continuously the page did seem to freeze while scrolling, but then after a few seconds it started working fine without any issues. Got a feeling that it is bit of a performance intensive action.

**Comment by rhyneav** [comment] 2018-08-16 22:26
Hmm, that might be the case. The checkbox and radio buttons are a background image. Maybe it's taking a few seconds for them to load.

**Comment by jeet-parekh** [comment] 2018-08-18 12:11
Still not working on firefox though. I'm testing on the [papercss docs website](https://www.getpapercss.com/docs/components/forms/). I even waited 30 seconds. That website definitely isn't performance hungry. I was able to scroll just fine. But couldn't toggle the check boxes and radio buttons.

**Comment by rhyneav** [comment] 2018-08-18 17:26
Hmm, I can try to take a look this weekend, but a PR is always welcome if anyone finds the fix!

**Comment by rhyneav** [comment] 2018-09-08 11:30
Fixed in [v1.5.2](https://github.com/papercss/papercss/releases/tag/v1.5.2)

**Closed by rhyneav** 2018-09-08 11:30 UTC
Labels: help wanted
